name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  weather_api_client:
    path: ../weather_api_client

  weather_local_storage:
    path: ../weather_local_storage

dev_dependencies:
  coverage: ^1.0.3
  mocktail: ^1.0.4
  test: ^1.25.2